name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Check go mod tidy
        run: |
          cp go.mod go.mod.bak
          make tidy
          diff go.mod go.mod.bak
          rm go.mod.bak

      - name: Test code
        run: go test -v ./...

      - name: Check lint
        uses: golangci/golangci-lint-action@v3
